import Footer from "../components/Footer";
import Header from "../components/Header";
import "./globals.css";
import { ProductContextProvider } from "../context/ProductContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col justify-between h-screen text-center ">
        <ProductContextProvider>
          <Header />
          {children}
          <Footer />
        </ProductContextProvider>
      </body>
    </html>
  );
}
